version: "3"

services:
  backend:
    env_file:
      - ../engconfig/engconfig.env
    image: hack4laengage/engage_backend_service:latest
    working_dir: /engage_backend_service
    entrypoint: ./scripts/runprod.sh
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:5.0.5-alpine